#!/usr/bin/env python3
"""Generate genetic_table.py from scripture.

The codon table, the nucleotide→B₄ map, and the twelve-fold bijection are not
retyped here — they are parsed out of the Lean that proves them, so V⊙x cannot
drift from the source. Run this when the Lean changes; commit what it writes.

    python3 gen_genetic_table.py PATH/TO/GeneticCode.lean
"""
import re
import sys

LEAN = sys.argv[1] if len(sys.argv) > 1 else (
    "../ig-docs/publishing/manuscripts/voynich_lifted/lean/GeneticCode.lean")
src = open(LEAN).read()

# nucleotide → Belnap
nuc = dict(re.findall(r"\|\s*\.(\w)\s*=>\s*\.(\w)", src.split("def nucToB4")[1]
                      .split("theorem")[0]))

# codon → meaning
body = src.split("def geneticCode")[1].split("\n\n")[0]
codons = {}
for a, b, c, kind, val in re.findall(
        r"\|\s*\(\.(\w),\.(\w),\.(\w)\)\s*=>\s*\.(aa|stop)\s+\.(\w+)", body):
    codons[a + b + c] = (kind, val)

# amino acid → IG primitive family
prim = dict(re.findall(r"\|\s*\.(\w+)\s*=>\s*some\s+\.(\w+)",
                       src.split("def aaToPrimitive")[1].split("def ")[0]))

# The slot order of the twelve, from the Imscriber's Guide: one glyph per axis.
SLOTS = ["Dimensionality", "Topology", "Relational", "Polarity", "Fidelity",
         "Kinetics", "Granularity", "Grammar", "Criticality", "Chirality",
         "Stoichiometry", "Protection"]
GLYPHS = ["⊢", "⊣", ">", "<", "⋈", "⊙", "∈", "∋", "⊤", "⊥", "⊞", "◻"]
# The genetics dialect names four axes differently. Same slots, same
# cardinality, different words — recorded, not reconciled away.
DIALECT = {"Recognition": "Relational", "Parity": "Polarity",
           "Coupling": "Grammar", "Winding": "Protection"}

# red-hot_rebis v0.6.0 (2026-06-03) revises three assignments, and the Lean
# parsed above predates it. The revision is a 3-cycle, so the bijection is
# preserved and no axis is left empty:
#
#   His  Granularity -> Criticality   imidazole pKa~6 is the only sidechain pKa
#                                     near physiological pH, so His is what
#                                     titrates at the acid/base crossover —
#                                     the critical point itself
#   Gln  Criticality -> Grammar       the long amide side chain's H-bond network
#                                     is what structures interaction patterns
#   Asn  Grammar     -> Granularity   N-glycosylation gates interaction RANGE
#
# Slot order is identical in both sources; red-hot_rebis writes slot 9 with the
# retired letter ⊙, which the current alphabet spells ⊤. Only the spelling
# differs there, not the position.
REVISION = {"His": "Criticality", "Gln": "Grammar", "Asn": "Granularity"}

aa_glyph = {}
for aa, family in prim.items():
    family = REVISION.get(aa, family)
    slot = SLOTS.index(DIALECT.get(family, family))
    aa_glyph[aa] = (GLYPHS[slot], family, slot)

out = ['"""Generated by gen_genetic_table.py from the Lean that proves it.',
       'Do not edit: fix the generator and regenerate."""', "",
       f"NUC_B4 = {nuc!r}", "",
       f"CODON = {codons!r}", "",
       "# amino acid -> (glyph, primitive family in the genetics dialect, slot)",
       f"AA_GLYPH = {aa_glyph!r}", "",
       f"DIALECT_DIVERGENCE = {DIALECT!r}", "",
       f"REVISION = {REVISION!r}", ""]
open("genetic_table.py", "w").write("\n".join(out))
print(f"wrote genetic_table.py: {len(codons)} codons, {len(nuc)} nucleotides, "
      f"{len(aa_glyph)} promoted amino acids")
