"""Generated by gen_genetic_table.py from the Lean that proves it.
Do not edit: fix the generator and regenerate."""

NUC_B4 = {'G': 'B', 'C': 'T', 'A': 'F', 'U': 'N'}

CODON = {'UUU': ('aa', 'Phe'), 'UUC': ('aa', 'Phe'), 'UUA': ('aa', 'Leu'), 'UUG': ('aa', 'Leu'), 'UCU': ('aa', 'Ser'), 'UCC': ('aa', 'Ser'), 'UCA': ('aa', 'Ser'), 'UCG': ('aa', 'Ser'), 'UAU': ('aa', 'Tyr'), 'UAC': ('aa', 'Tyr'), 'UAA': ('stop', 'UAA'), 'UAG': ('stop', 'UAG'), 'UGU': ('aa', 'Cys'), 'UGC': ('aa', 'Cys'), 'UGA': ('stop', 'UGA'), 'UGG': ('aa', 'Trp'), 'CUU': ('aa', 'Leu'), 'CUC': ('aa', 'Leu'), 'CUA': ('aa', 'Leu'), 'CUG': ('aa', 'Leu'), 'CCU': ('aa', 'Pro'), 'CCC': ('aa', 'Pro'), 'CCA': ('aa', 'Pro'), 'CCG': ('aa', 'Pro'), 'CAU': ('aa', 'His'), 'CAC': ('aa', 'His'), 'CAA': ('aa', 'Gln'), 'CAG': ('aa', 'Gln'), 'CGU': ('aa', 'Arg'), 'CGC': ('aa', 'Arg'), 'CGA': ('aa', 'Arg'), 'CGG': ('aa', 'Arg'), 'AUU': ('aa', 'Ile'), 'AUC': ('aa', 'Ile'), 'AUA': ('aa', 'Ile'), 'AUG': ('aa', 'Met'), 'ACU': ('aa', 'Thr'), 'ACC': ('aa', 'Thr'), 'ACA': ('aa', 'Thr'), 'ACG': ('aa', 'Thr'), 'AAU': ('aa', 'Asn'), 'AAC': ('aa', 'Asn'), 'AAA': ('aa', 'Lys'), 'AAG': ('aa', 'Lys'), 'AGU': ('aa', 'Ser'), 'AGC': ('aa', 'Ser'), 'AGA': ('aa', 'Arg'), 'AGG': ('aa', 'Arg'), 'GUU': ('aa', 'Val'), 'GUC': ('aa', 'Val'), 'GUA': ('aa', 'Val'), 'GUG': ('aa', 'Val'), 'GCU': ('aa', 'Ala'), 'GCC': ('aa', 'Ala'), 'GCA': ('aa', 'Ala'), 'GCG': ('aa', 'Ala'), 'GAU': ('aa', 'Asp'), 'GAC': ('aa', 'Asp'), 'GAA': ('aa', 'Glu'), 'GAG': ('aa', 'Glu'), 'GGU': ('aa', 'Gly'), 'GGC': ('aa', 'Gly'), 'GGA': ('aa', 'Gly'), 'GGG': ('aa', 'Gly')}

# amino acid -> (glyph, primitive family in the genetics dialect, slot)
AA_GLYPH = {'Met': ('⊢', 'Dimensionality', 0), 'Trp': ('⊣', 'Topology', 1), 'Cys': ('>', 'Recognition', 2), 'Tyr': ('<', 'Parity', 3), 'Phe': ('⋈', 'Fidelity', 4), 'Ile': ('⊤', 'Kinetics', 5), 'His': ('⊙', 'Criticality', 8), 'Asn': ('∈', 'Granularity', 6), 'Gln': ('∋', 'Grammar', 7), 'Asp': ('⊥', 'Chirality', 9), 'Lys': ('⊞', 'Stoichiometry', 10), 'Glu': ('◻', 'Winding', 11)}

DIALECT_DIVERGENCE = {'Recognition': 'Relational', 'Parity': 'Polarity', 'Coupling': 'Grammar', 'Winding': 'Protection'}

REVISION = {'His': 'Criticality', 'Gln': 'Grammar', 'Asn': 'Granularity'}
